### ISSUE TITLE
Fractions: Equality master checklist

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/fractions-equality#1]
## Design
- [x] **Sim folder and design doc created** (Date: //) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed**
- [x] **Learning goals and standards identified** (Date: //)
- [x] **Design concept complete**  (Date: //)
- [x] **Wireframes complete** (Date: //) 
- [x] **Mockups complete** (Date: //) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion** N/A
- [ ] **Interviews complete** (Date: //) - interviews skipped since this was an exact copy of the Java sim
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: //) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] Add an activity
  - [ ] Sim primer draft
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [x] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Post-publication items** 
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim)

## Implementation
- [x] **Repository created** (Date: 03/19/2018)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 03/19/2018)
- [x] **Sim is "feature complete"** (Date: 12/15/2018)
- [x] **Code review completed** (Date: 12/24/2018) 
- [x] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Verify credits
- [x] **Published** (Date: 01/29/2019) 
  - [x] README.md updated using `grunt published-README` (in master and release branch)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
 
## QA
- [x] **Dev testing started** (Date: 01/03/2019) 
- [x] **Dev testing completed** (Date: 01/08/2019) 
- [x] **First RC published** (Date: 01/16/2019)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 01/28/2019)

**Comment by jonathanolson** [comment]
Sim has been published. I filled out the implementation section. @ariel-phet should this be closed or filled out?
